animations {
    enabled = yes

    # Default bezier curve
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    # Windows
    animation = windows, 1, 7, myBezier
    animation = windowsIn, 1, 7, myBezier, slide
    animation = windowsOut, 1, 7, myBezier, popin 80%
    animation = windowsMove, 1, 7, myBezier

    # Layers
    animation = layers, 1, 6, default, fade
    animation = layersIn, 1, 6, default, fade
    animation = layersOut, 1, 6, default, fade

    # Fade
    animation = fade, 1, 7, default
    animation = fadeIn, 1, 7, default
    animation = fadeOut, 1, 7, default
    animation = fadeSwitch, 1, 7, default
    animation = fadeShadow, 1, 7, default
    animation = fadeDim, 1, 7, default
    animation = fadeLayers, 1, 7, default
    animation = fadeLayersIn, 1, 7, default
    animation = fadeLayersOut, 1, 7, default
    animation = fadePopups, 1, 7, default
    animation = fadePopupsIn, 1, 7, default
    animation = fadePopupsOut, 1, 7, default
    animation = fadeDpms, 1, 7, default

    # Border and Angle
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default, loop

    # Workspaces
    animation = workspaces, 1, 6, default
    animation = workspacesIn, 1, 6, default
    animation = workspacesOut, 1, 6, default
    animation = specialWorkspace, 1, 6, default, slidefadevert 20%
    animation = specialWorkspaceIn, 1, 6, default, slidefadevert 20%
    animation = specialWorkspaceOut, 1, 6, default, slidefadevert 20%

    # Misc
    animation = zoomFactor, 1, 6, default
    animation = monitorAdded, 1, 6, default
}
