source = ~/.config/hypr/configs/binds.conf
source = ~/.config/hypr/configs/animations.conf
source = ~/.config/hypr/configs/monitors.conf
source = ~/.config/hypr/configs/startup.conf
source = ~/.config/hypr/configs/decor.conf
